### ISSUE TITLE
Compilation error with python3.4

### ISSUE THREAD

**Issue by AleksTk** [AleksTk/varint#1]
Looks like PyFile_AsFile is not defined in python3.4 : http://stackoverflow.com/questions/16130268/python-3-replacement-for-pyfile-asfile#16132269

$ python setup.py build_ext --inplace

running build_ext
building 'varinttest._varint' extension
swigging varinttest/varint.i to varinttest/varint_wrap.c
swig -python -o varinttest/varint_wrap.c varinttest/varint.i
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.4m -c src/varint.c -o build/temp.linux-x86_64-3.4/src/varint.o
src/varint.c: In function ‘varint_read’:
src/varint.c:45:2: error: unknown type name ‘PyFileObject’
  PyFileObject* p2 = (PyFileObject*) p;
  ^
src/varint.c:45:22: error: ‘PyFileObject’ undeclared (first use in this function)
  PyFileObject* p2 = (PyFileObject*) p;
                      ^
src/varint.c:45:22: note: each undeclared identifier is reported only once for each function it appears in
src/varint.c:45:35: error: expected expression before ‘)’ token
  PyFileObject* p2 = (PyFileObject*) p;
                                   ^
src/varint.c:46:2: warning: implicit declaration of function ‘PyFile_AsFile’ [-Wimplicit-function-declaration]
  FILE* f = PyFile_AsFile(p);
  ^
src/varint.c:46:12: warning: initialization makes pointer from integer without a cast [enabled by default]
  FILE* f = PyFile_AsFile(p);
            ^
src/varint.c:47:2: warning: implicit declaration of function ‘PyFile_IncUseCount’ [-Wimplicit-function-declaration]
  PyFile_IncUseCount(p2);
  ^
src/varint.c:49:2: warning: implicit declaration of function ‘PyFile_DecUseCount’ [-Wimplicit-function-declaration]
  PyFile_DecUseCount(p2);
  ^
src/varint.c: In function ‘varint_write’:
src/varint.c:54:2: error: unknown type name ‘PyFileObject’
  PyFileObject* p2 = (PyFileObject*) p;
  ^
src/varint.c:54:22: error: ‘PyFileObject’ undeclared (first use in this function)
  PyFileObject* p2 = (PyFileObject*) p;
                      ^
src/varint.c:54:35: error: expected expression before ‘)’ token
  PyFileObject* p2 = (PyFileObject*) p;
                                   ^
src/varint.c:55:12: warning: initialization makes pointer from integer without a cast [enabled by default]
  FILE* f = PyFile_AsFile(p);
            ^
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

**Comment by ds-dev** [comment]
# Fixed, rewritten to Python3.x API, backward compatibility with 2.7 preserved.
# Building 2.7, as usual: 
python setup.py build_ext --inplace
# Building 3.x: 
CFLAGS='-DHAVE_PYTHON3' python3 setup.py build_ext --inplace
